playlists = {
   "href":"https://api.spotify.com/v1/users/9n5x13bh8zmxmhb8kgea3d9xn/playlists?offset=0&limit=50",
   "items":[
      {
         "collaborative":False,
         "description":"",
         "external_urls":{
            "spotify":"https://open.spotify.com/playlist/2NPt11BnuqkJs4vFcpwVhM"
         },
         "href":"https://api.spotify.com/v1/playlists/2NPt11BnuqkJs4vFcpwVhM",
         "id":"2NPt11BnuqkJs4vFcpwVhM",
         "images":[
            {
               "height":640,
               "url":"https://mosaic.scdn.co/640/ab67616d0000b273365b3fb800c19f7ff72602daab67616d0000b2733bcf586e8df6f8ef4a36ca3cab67616d0000b273b5d9c8de465654c20d77305cab67616d0000b273b6866de8f1c7a1a1559ef5a8",
               "width":640
            }
         ],
         "name":"R&B",
         "primary_color":"None",
         "public":True,
         "snapshot_id":"NCwzMWY3N2EzY2E2ZDkwYTEwZGMyOWY4YTJlZjM0ZjBjOTJmNDNjMjMx",
         "tracks":{
            "href":"https://api.spotify.com/v1/playlists/2NPt11BnuqkJs4vFcpwVhM/tracks",
            "total":9
         },
         "type":"playlist",
         "uri":"spotify:playlist:2NPt11BnuqkJs4vFcpwVhM"
      },
      {
         "collaborative":False,
         "description":"",
         "external_urls":{
            "spotify":"https://open.spotify.com/playlist/095QFFveXszAS9giwN6Zhe"
         },
         "href":"https://api.spotify.com/v1/playlists/095QFFveXszAS9giwN6Zhe",
         "id":"095QFFveXszAS9giwN6Zhe",
         "images":[
            {
               "height":640,
               "url":"https://mosaic.scdn.co/640/ab67616d0000b27331aa3ebe23f59778bff800c9ab67616d0000b273712701c5e263efc8726b1464ab67616d0000b273a91c10fe9472d9bd89802e5aab67616d0000b273e6f407c7f3a0ec98845e4431",
               "width":640
            }
         ],
         "name":"Pop",
         "primary_color":"None",
         "public":True,
         "snapshot_id":"MyxmNGRjNTI5Njg4Yzc0NTgxMWQ5ZjE0NjUwMmM3ZmNlYjc5MDMxMzdl",
         "tracks":{
            "href":"https://api.spotify.com/v1/playlists/095QFFveXszAS9giwN6Zhe/tracks",
            "total":16
         },
         "type":"playlist",
         "uri":"spotify:playlist:095QFFveXszAS9giwN6Zhe"
      },
      {
         "collaborative":False,
         "description":"",
         "external_urls":{
            "spotify":"https://open.spotify.com/playlist/6s9cxDLqCtgbHsyDtdGgqz"
         },
         "href":"https://api.spotify.com/v1/playlists/6s9cxDLqCtgbHsyDtdGgqz",
         "id":"6s9cxDLqCtgbHsyDtdGgqz",
         "images":[
            {
               "height":640,
               "url":"https://mosaic.scdn.co/640/ab67616d0000b2731be40e44db112e123e5e8b51ab67616d0000b27330d45198d0c9e8841f9a9578ab67616d0000b27374d9a833744be96426ee833cab67616d0000b2739dcf31d6b5eb82fa24de783a",
               "width":640
            }
         ],
         "name":"Rock",
         "primary_color":"None",
         "public":True,
         "snapshot_id":"MyxhMTI0YmExN2MyZTQzNDZiODJkMTRiMDZhYzQxODFkYTYyZjQyZGU3",
         "tracks":{
            "href":"https://api.spotify.com/v1/playlists/6s9cxDLqCtgbHsyDtdGgqz/tracks",
            "total":17
         },
         "type":"playlist",
         "uri":"spotify:playlist:6s9cxDLqCtgbHsyDtdGgqz"
      }
   ],
   "limit":50,
   "next":"None",
   "offset":0,
   "previous":"None",
   "total":3
}

top = {
   "items":[
      {
         "album":{
            "album_type":"ALBUM",
            "artists":[
               {
                  "external_urls":{
                     "spotify":"https://open.spotify.com/artist/3jK9MiCrA42lLAdMGUZpwa"
                  },
                  "href":"https://api.spotify.com/v1/artists/3jK9MiCrA42lLAdMGUZpwa",
                  "id":"3jK9MiCrA42lLAdMGUZpwa",
                  "name":"Anderson .Paak",
                  "type":"artist",
                  "uri":"spotify:artist:3jK9MiCrA42lLAdMGUZpwa"
               }
            ],
            "external_urls":{
               "spotify":"https://open.spotify.com/album/4VFG1DOuTeDMBjBLZT7hCK"
            },
            "href":"https://api.spotify.com/v1/albums/4VFG1DOuTeDMBjBLZT7hCK",
            "id":"4VFG1DOuTeDMBjBLZT7hCK",
            "images":[
               {
                  "height":640,
                  "url":"https://i.scdn.co/image/ab67616d0000b273f8e77075414234fd77fce32b",
                  "width":640
               },
               {
                  "height":300,
                  "url":"https://i.scdn.co/image/ab67616d00001e02f8e77075414234fd77fce32b",
                  "width":300
               },
               {
                  "height":64,
                  "url":"https://i.scdn.co/image/ab67616d00004851f8e77075414234fd77fce32b",
                  "width":64
               }
            ],
            "name":"Malibu",
            "release_date":"2016-01-15",
            "release_date_precision":"day",
            "total_tracks":16,
            "type":"album",
            "uri":"spotify:album:4VFG1DOuTeDMBjBLZT7hCK"
         },
         "artists":[
            {
               "external_urls":{
                  "spotify":"https://open.spotify.com/artist/3jK9MiCrA42lLAdMGUZpwa"
               },
               "href":"https://api.spotify.com/v1/artists/3jK9MiCrA42lLAdMGUZpwa",
               "id":"3jK9MiCrA42lLAdMGUZpwa",
               "name":"Anderson .Paak",
               "type":"artist",
               "uri":"spotify:artist:3jK9MiCrA42lLAdMGUZpwa"
            }
         ],
         "disc_number":1,
         "duration_ms":328813,
         "explicit":True,
         "external_ids":{
            "isrc":"USUYG1088416"
         },
         "external_urls":{
            "spotify":"https://open.spotify.com/track/5G0nSEIT0fGUZY0caM9AnH"
         },
         "href":"https://api.spotify.com/v1/tracks/5G0nSEIT0fGUZY0caM9AnH",
         "id":"5G0nSEIT0fGUZY0caM9AnH",
         "is_local":False,
         "name":"The Season | Carry Me",
         "popularity":52,
         "preview_url":"https://p.scdn.co/mp3-preview/03ed34a366cd1b0e0bb5a27f2ee44335c75027a4?cid=26c35b7190da459584f5534423c51888",
         "track_number":4,
         "type":"track",
         "uri":"spotify:track:5G0nSEIT0fGUZY0caM9AnH"
      },
      {
         "album":{
            "album_type":"SINGLE",
            "artists":[
               {
                  "external_urls":{
                     "spotify":"https://open.spotify.com/artist/6yby1ACnfwVigbSSaH3kEQ"
                  },
                  "href":"https://api.spotify.com/v1/artists/6yby1ACnfwVigbSSaH3kEQ",
                  "id":"6yby1ACnfwVigbSSaH3kEQ",
                  "name":"City Girl",
                  "type":"artist",
                  "uri":"spotify:artist:6yby1ACnfwVigbSSaH3kEQ"
               },
               {
                  "external_urls":{
                     "spotify":"https://open.spotify.com/artist/0u2qphtOdF2T2YWmi74O0P"
                  },
                  "href":"https://api.spotify.com/v1/artists/0u2qphtOdF2T2YWmi74O0P",
                  "id":"0u2qphtOdF2T2YWmi74O0P",
                  "name":"ry",
                  "type":"artist",
                  "uri":"spotify:artist:0u2qphtOdF2T2YWmi74O0P"
               },
               {
                  "external_urls":{
                     "spotify":"https://open.spotify.com/artist/4bQCZKbtYa0W0hzA7JrpC4"
                  },
                  "href":"https://api.spotify.com/v1/artists/4bQCZKbtYa0W0hzA7JrpC4",
                  "id":"4bQCZKbtYa0W0hzA7JrpC4",
                  "name":"tiffi",
                  "type":"artist",
                  "uri":"spotify:artist:4bQCZKbtYa0W0hzA7JrpC4"
               }
            ],
            "external_urls":{
               "spotify":"https://open.spotify.com/album/4Dz3IfBy36UQkWvsReGFlH"
            },
            "href":"https://api.spotify.com/v1/albums/4Dz3IfBy36UQkWvsReGFlH",
            "id":"4Dz3IfBy36UQkWvsReGFlH",
            "images":[
               {
                  "height":640,
                  "url":"https://i.scdn.co/image/ab67616d0000b273fbd735f5038edcd15e6cfd8d",
                  "width":640
               },
               {
                  "height":300,
                  "url":"https://i.scdn.co/image/ab67616d00001e02fbd735f5038edcd15e6cfd8d",
                  "width":300
               },
               {
                  "height":64,
                  "url":"https://i.scdn.co/image/ab67616d00004851fbd735f5038edcd15e6cfd8d",
                  "width":64
               }
            ],
            "name":"Wishing on You",
            "release_date":"2020-07-08",
            "release_date_precision":"day",
            "total_tracks":1,
            "type":"album",
            "uri":"spotify:album:4Dz3IfBy36UQkWvsReGFlH"
         },
         "artists":[
            {
               "external_urls":{
                  "spotify":"https://open.spotify.com/artist/6yby1ACnfwVigbSSaH3kEQ"
               },
               "href":"https://api.spotify.com/v1/artists/6yby1ACnfwVigbSSaH3kEQ",
               "id":"6yby1ACnfwVigbSSaH3kEQ",
               "name":"City Girl",
               "type":"artist",
               "uri":"spotify:artist:6yby1ACnfwVigbSSaH3kEQ"
            },
            {
               "external_urls":{
                  "spotify":"https://open.spotify.com/artist/0u2qphtOdF2T2YWmi74O0P"
               },
               "href":"https://api.spotify.com/v1/artists/0u2qphtOdF2T2YWmi74O0P",
               "id":"0u2qphtOdF2T2YWmi74O0P",
               "name":"ry",
               "type":"artist",
               "uri":"spotify:artist:0u2qphtOdF2T2YWmi74O0P"
            },
            {
               "external_urls":{
                  "spotify":"https://open.spotify.com/artist/4bQCZKbtYa0W0hzA7JrpC4"
               },
               "href":"https://api.spotify.com/v1/artists/4bQCZKbtYa0W0hzA7JrpC4",
               "id":"4bQCZKbtYa0W0hzA7JrpC4",
               "name":"tiffi",
               "type":"artist",
               "uri":"spotify:artist:4bQCZKbtYa0W0hzA7JrpC4"
            }
         ],
         "disc_number":1,
         "duration_ms":149250,
         "explicit":True,
         "external_ids":{
            "isrc":"QZHN82077346"
         },
         "external_urls":{
            "spotify":"https://open.spotify.com/track/0pfKMQx7WAdaLPCZJIDrah"
         },
         "href":"https://api.spotify.com/v1/tracks/0pfKMQx7WAdaLPCZJIDrah",
         "id":"0pfKMQx7WAdaLPCZJIDrah",
         "is_local":False,
         "name":"Wishing on You",
         "popularity":41,
         "preview_url":"https://p.scdn.co/mp3-preview/fda77fdf0cbad78c00423facae0dd8aeb58c7606?cid=26c35b7190da459584f5534423c51888",
         "track_number":1,
         "type":"track",
         "uri":"spotify:track:0pfKMQx7WAdaLPCZJIDrah"
      },
      {
         "album":{
            "album_type":"ALBUM",
            "artists":[
               {
                  "external_urls":{
                     "spotify":"https://open.spotify.com/artist/6xt9sJmmyYwWkJv8A6ssiU"
                  },
                  "href":"https://api.spotify.com/v1/artists/6xt9sJmmyYwWkJv8A6ssiU",
                  "id":"6xt9sJmmyYwWkJv8A6ssiU",
                  "name":"Cory Wong",
                  "type":"artist",
                  "uri":"spotify:artist:6xt9sJmmyYwWkJv8A6ssiU"
               }
            ],
            "external_urls":{
               "spotify":"https://open.spotify.com/album/6DoHXjDY8U748166kiW8J3"
            },
            "href":"https://api.spotify.com/v1/albums/6DoHXjDY8U748166kiW8J3",
            "id":"6DoHXjDY8U748166kiW8J3",
            "images":[
               {
                  "height":640,
                  "url":"https://i.scdn.co/image/ab67616d0000b273b463af42916ee046df8694e3",
                  "width":640
               },
               {
                  "height":300,
                  "url":"https://i.scdn.co/image/ab67616d00001e02b463af42916ee046df8694e3",
                  "width":300
               },
               {
                  "height":64,
                  "url":"https://i.scdn.co/image/ab67616d00004851b463af42916ee046df8694e3",
                  "width":64
               }
            ],
            "name":"Cory and the Wongnotes",
            "release_date":"2021-02-05",
            "release_date_precision":"day",
            "total_tracks":11,
            "type":"album",
            "uri":"spotify:album:6DoHXjDY8U748166kiW8J3"
         },
         "artists":[
            {
               "external_urls":{
                  "spotify":"https://open.spotify.com/artist/6xt9sJmmyYwWkJv8A6ssiU"
               },
               "href":"https://api.spotify.com/v1/artists/6xt9sJmmyYwWkJv8A6ssiU",
               "id":"6xt9sJmmyYwWkJv8A6ssiU",
               "name":"Cory Wong",
               "type":"artist",
               "uri":"spotify:artist:6xt9sJmmyYwWkJv8A6ssiU"
            }
         ],
         "disc_number":1,
         "duration_ms":234462,
         "explicit":False,
         "external_ids":{
            "isrc":"QZFYW2196614"
         },
         "external_urls":{
            "spotify":"https://open.spotify.com/track/7zq1YbMIklTQ3GZWG6ICg1"
         },
         "href":"https://api.spotify.com/v1/tracks/7zq1YbMIklTQ3GZWG6ICg1",
         "id":"7zq1YbMIklTQ3GZWG6ICg1",
         "is_local":False,
         "name":"Starfire",
         "popularity":30,
         "preview_url":"https://p.scdn.co/mp3-preview/5a663d6b1b0a173d0e158ab0a368ec95253ef4d2?cid=26c35b7190da459584f5534423c51888",
         "track_number":6,
         "type":"track",
         "uri":"spotify:track:7zq1YbMIklTQ3GZWG6ICg1"
      },
      {
         "album":{
            "album_type":"ALBUM",
            "artists":[
               {
                  "external_urls":{
                     "spotify":"https://open.spotify.com/artist/2FdiOm1d5IVBdLlobhzlTF"
                  },
                  "href":"https://api.spotify.com/v1/artists/2FdiOm1d5IVBdLlobhzlTF",
                  "id":"2FdiOm1d5IVBdLlobhzlTF",
                  "name":"Kingo Hamada",
                  "type":"artist",
                  "uri":"spotify:artist:2FdiOm1d5IVBdLlobhzlTF"
               }
            ],
            "external_urls":{
               "spotify":"https://open.spotify.com/album/30lgWjklkY1TOx7EdiGYlq"
            },
            "href":"https://api.spotify.com/v1/albums/30lgWjklkY1TOx7EdiGYlq",
            "id":"30lgWjklkY1TOx7EdiGYlq",
            "images":[
               {
                  "height":640,
                  "url":"https://i.scdn.co/image/ab67616d0000b27399c0ecaf5aca482a51acf628",
                  "width":640
               },
               {
                  "height":300,
                  "url":"https://i.scdn.co/image/ab67616d00001e0299c0ecaf5aca482a51acf628",
                  "width":300
               },
               {
                  "height":64,
                  "url":"https://i.scdn.co/image/ab67616d0000485199c0ecaf5aca482a51acf628",
                  "width":64
               }
            ],
            "name":"midnight cruisin'",
            "release_date":"1982-10-21",
            "release_date_precision":"day",
            "total_tracks":9,
            "type":"album",
            "uri":"spotify:album:30lgWjklkY1TOx7EdiGYlq"
         },
         "artists":[
            {
               "external_urls":{
                  "spotify":"https://open.spotify.com/artist/2FdiOm1d5IVBdLlobhzlTF"
               },
               "href":"https://api.spotify.com/v1/artists/2FdiOm1d5IVBdLlobhzlTF",
               "id":"2FdiOm1d5IVBdLlobhzlTF",
               "name":"Kingo Hamada",
               "type":"artist",
               "uri":"spotify:artist:2FdiOm1d5IVBdLlobhzlTF"
            }
         ],
         "disc_number":1,
         "duration_ms":283000,
         "explicit":False,
         "external_ids":{
            "isrc":"JPAM08200060"
         },
         "external_urls":{
            "spotify":"https://open.spotify.com/track/37NPLfEZQQ0rZTa9SRqWBL"
         },
         "href":"https://api.spotify.com/v1/tracks/37NPLfEZQQ0rZTa9SRqWBL",
         "id":"37NPLfEZQQ0rZTa9SRqWBL",
         "is_local":False,
         "name":"midnight cruisin'",
         "popularity":54,
         "preview_url":"https://p.scdn.co/mp3-preview/e0f1059c2de3c578e9f6a636a3779db4d784781e?cid=26c35b7190da459584f5534423c51888",
         "track_number":6,
         "type":"track",
         "uri":"spotify:track:37NPLfEZQQ0rZTa9SRqWBL"
      },
      {
         "album":{
            "album_type":"ALBUM",
            "artists":[
               {
                  "external_urls":{
                     "spotify":"https://open.spotify.com/artist/0du5cEVh5yTK9QJze8zA0C"
                  },
                  "href":"https://api.spotify.com/v1/artists/0du5cEVh5yTK9QJze8zA0C",
                  "id":"0du5cEVh5yTK9QJze8zA0C",
                  "name":"Bruno Mars",
                  "type":"artist",
                  "uri":"spotify:artist:0du5cEVh5yTK9QJze8zA0C"
               },
               {
                  "external_urls":{
                     "spotify":"https://open.spotify.com/artist/3jK9MiCrA42lLAdMGUZpwa"
                  },
                  "href":"https://api.spotify.com/v1/artists/3jK9MiCrA42lLAdMGUZpwa",
                  "id":"3jK9MiCrA42lLAdMGUZpwa",
                  "name":"Anderson .Paak",
                  "type":"artist",
                  "uri":"spotify:artist:3jK9MiCrA42lLAdMGUZpwa"
               },
               {
                  "external_urls":{
                     "spotify":"https://open.spotify.com/artist/6PvvGcCY2XtUcSRld1Wilr"
                  },
                  "href":"https://api.spotify.com/v1/artists/6PvvGcCY2XtUcSRld1Wilr",
                  "id":"6PvvGcCY2XtUcSRld1Wilr",
                  "name":"Silk Sonic",
                  "type":"artist",
                  "uri":"spotify:artist:6PvvGcCY2XtUcSRld1Wilr"
               }
            ],
            "external_urls":{
               "spotify":"https://open.spotify.com/album/0S0r2RFucaW9kVjBtcBOV1"
            },
            "href":"https://api.spotify.com/v1/albums/0S0r2RFucaW9kVjBtcBOV1",
            "id":"0S0r2RFucaW9kVjBtcBOV1",
            "images":[
               {
                  "height":640,
                  "url":"https://i.scdn.co/image/ab67616d0000b27310f084209eab3dfecf7d5f8e",
                  "width":640
               },
               {
                  "height":300,
                  "url":"https://i.scdn.co/image/ab67616d00001e0210f084209eab3dfecf7d5f8e",
                  "width":300
               },
               {
                  "height":64,
                  "url":"https://i.scdn.co/image/ab67616d0000485110f084209eab3dfecf7d5f8e",
                  "width":64
               }
            ],
            "name":"An Evening With Silk Sonic",
            "release_date":"2021-11-12",
            "release_date_precision":"day",
            "total_tracks":9,
            "type":"album",
            "uri":"spotify:album:0S0r2RFucaW9kVjBtcBOV1"
         },
         "artists":[
            {
               "external_urls":{
                  "spotify":"https://open.spotify.com/artist/0du5cEVh5yTK9QJze8zA0C"
               },
               "href":"https://api.spotify.com/v1/artists/0du5cEVh5yTK9QJze8zA0C",
               "id":"0du5cEVh5yTK9QJze8zA0C",
               "name":"Bruno Mars",
               "type":"artist",
               "uri":"spotify:artist:0du5cEVh5yTK9QJze8zA0C"
            },
            {
               "external_urls":{
                  "spotify":"https://open.spotify.com/artist/3jK9MiCrA42lLAdMGUZpwa"
               },
               "href":"https://api.spotify.com/v1/artists/3jK9MiCrA42lLAdMGUZpwa",
               "id":"3jK9MiCrA42lLAdMGUZpwa",
               "name":"Anderson .Paak",
               "type":"artist",
               "uri":"spotify:artist:3jK9MiCrA42lLAdMGUZpwa"
            },
            {
               "external_urls":{
                  "spotify":"https://open.spotify.com/artist/6PvvGcCY2XtUcSRld1Wilr"
               },
               "href":"https://api.spotify.com/v1/artists/6PvvGcCY2XtUcSRld1Wilr",
               "id":"6PvvGcCY2XtUcSRld1Wilr",
               "name":"Silk Sonic",
               "type":"artist",
               "uri":"spotify:artist:6PvvGcCY2XtUcSRld1Wilr"
            },
            {
               "external_urls":{
                  "spotify":"https://open.spotify.com/artist/4frXpPxQQZwbCu3eTGnZEw"
               },
               "href":"https://api.spotify.com/v1/artists/4frXpPxQQZwbCu3eTGnZEw",
               "id":"4frXpPxQQZwbCu3eTGnZEw",
               "name":"Thundercat",
               "type":"artist",
               "uri":"spotify:artist:4frXpPxQQZwbCu3eTGnZEw"
            },
            {
               "external_urls":{
                  "spotify":"https://open.spotify.com/artist/5K0rbdBrs2tNXe5LeWMATT"
               },
               "href":"https://api.spotify.com/v1/artists/5K0rbdBrs2tNXe5LeWMATT",
               "id":"5K0rbdBrs2tNXe5LeWMATT",
               "name":"Bootsy Collins",
               "type":"artist",
               "uri":"spotify:artist:5K0rbdBrs2tNXe5LeWMATT"
            }
         ],
         "disc_number":1,
         "duration_ms":249444,
         "explicit":False,
         "external_ids":{
            "isrc":"USAT22103103"
         },
         "external_urls":{
            "spotify":"https://open.spotify.com/track/0crw01bqnefvDUDjsuKraD"
         },
         "href":"https://api.spotify.com/v1/tracks/0crw01bqnefvDUDjsuKraD",
         "id":"0crw01bqnefvDUDjsuKraD",
         "is_local":False,
         "name":"After Last Night (with Thundercat & Bootsy Collins)",
         "popularity":77,
         "preview_url":"https://p.scdn.co/mp3-preview/154dd52bdcb5e4d8c0f5a63acf62f5b6ba5c28c3?cid=26c35b7190da459584f5534423c51888",
         "track_number":4,
         "type":"track",
         "uri":"spotify:track:0crw01bqnefvDUDjsuKraD"
      },
      {
         "album":{
            "album_type":"ALBUM",
            "artists":[
               {
                  "external_urls":{
                     "spotify":"https://open.spotify.com/artist/0xGtOrmB2hnrNRLG3vhpSo"
                  },
                  "href":"https://api.spotify.com/v1/artists/0xGtOrmB2hnrNRLG3vhpSo",
                  "id":"0xGtOrmB2hnrNRLG3vhpSo",
                  "name":"Anri",
                  "type":"artist",
                  "uri":"spotify:artist:0xGtOrmB2hnrNRLG3vhpSo"
               }
            ],
            "external_urls":{
               "spotify":"https://open.spotify.com/album/3OvZYx7AAGplmJjwD29JiV"
            },
            "href":"https://api.spotify.com/v1/albums/3OvZYx7AAGplmJjwD29JiV",
            "id":"3OvZYx7AAGplmJjwD29JiV",
            "images":[
               {
                  "height":640,
                  "url":"https://i.scdn.co/image/ab67616d0000b273cfd93d36fe2365f9436587d1",
                  "width":640
               },
               {
                  "height":300,
                  "url":"https://i.scdn.co/image/ab67616d00001e02cfd93d36fe2365f9436587d1",
                  "width":300
               },
               {
                  "height":64,
                  "url":"https://i.scdn.co/image/ab67616d00004851cfd93d36fe2365f9436587d1",
                  "width":64
               }
            ],
            "name":"Timely!!",
            "release_date":"1983-12-05",
            "release_date_precision":"day",
            "total_tracks":11,
            "type":"album",
            "uri":"spotify:album:3OvZYx7AAGplmJjwD29JiV"
         },
         "artists":[
            {
               "external_urls":{
                  "spotify":"https://open.spotify.com/artist/0xGtOrmB2hnrNRLG3vhpSo"
               },
               "href":"https://api.spotify.com/v1/artists/0xGtOrmB2hnrNRLG3vhpSo",
               "id":"0xGtOrmB2hnrNRLG3vhpSo",
               "name":"Anri",
               "type":"artist",
               "uri":"spotify:artist:0xGtOrmB2hnrNRLG3vhpSo"
            }
         ],
         "disc_number":1,
         "duration_ms":295666,
         "explicit":False,
         "external_ids":{
            "isrc":"JPFL08310230"
         },
         "external_urls":{
            "spotify":"https://open.spotify.com/track/1qUo7d5lAOclNVbTUY0A2R"
         },
         "href":"https://api.spotify.com/v1/tracks/1qUo7d5lAOclNVbTUY0A2R",
         "id":"1qUo7d5lAOclNVbTUY0A2R",
         "is_local":False,
         "name":"Remember Summer Days",
         "popularity":62,
         "preview_url":"https://p.scdn.co/mp3-preview/11c1efb44b02609b5b7416be1570b86d4502e364?cid=26c35b7190da459584f5534423c51888",
         "track_number":11,
         "type":"track",
         "uri":"spotify:track:1qUo7d5lAOclNVbTUY0A2R"
      },
      {
         "album":{
            "album_type":"SINGLE",
            "artists":[
               {
                  "external_urls":{
                     "spotify":"https://open.spotify.com/artist/3OvevnaMKTcWEKhxnYPIru"
                  },
                  "href":"https://api.spotify.com/v1/artists/3OvevnaMKTcWEKhxnYPIru",
                  "id":"3OvevnaMKTcWEKhxnYPIru",
                  "name":"Falqo",
                  "type":"artist",
                  "uri":"spotify:artist:3OvevnaMKTcWEKhxnYPIru"
               }
            ],
            "external_urls":{
               "spotify":"https://open.spotify.com/album/0DLQ1wt7WQaNaP1s132H3z"
            },
            "href":"https://api.spotify.com/v1/albums/0DLQ1wt7WQaNaP1s132H3z",
            "id":"0DLQ1wt7WQaNaP1s132H3z",
            "images":[
               {
                  "height":640,
                  "url":"https://i.scdn.co/image/ab67616d0000b273f58f629a3e278bd7bdbaba45",
                  "width":640
               },
               {
                  "height":300,
                  "url":"https://i.scdn.co/image/ab67616d00001e02f58f629a3e278bd7bdbaba45",
                  "width":300
               },
               {
                  "height":64,
                  "url":"https://i.scdn.co/image/ab67616d00004851f58f629a3e278bd7bdbaba45",
                  "width":64
               }
            ],
            "name":"Across the Sea",
            "release_date":"2016-03-14",
            "release_date_precision":"day",
            "total_tracks":1,
            "type":"album",
            "uri":"spotify:album:0DLQ1wt7WQaNaP1s132H3z"
         },
         "artists":[
            {
               "external_urls":{
                  "spotify":"https://open.spotify.com/artist/3OvevnaMKTcWEKhxnYPIru"
               },
               "href":"https://api.spotify.com/v1/artists/3OvevnaMKTcWEKhxnYPIru",
               "id":"3OvevnaMKTcWEKhxnYPIru",
               "name":"Falqo",
               "type":"artist",
               "uri":"spotify:artist:3OvevnaMKTcWEKhxnYPIru"
            }
         ],
         "disc_number":1,
         "duration_ms":273122,
         "explicit":False,
         "external_ids":{
            "isrc":"AUUSH1600004"
         },
         "external_urls":{
            "spotify":"https://open.spotify.com/track/6NXW1J0rvUBX7JprJg31H3"
         },
         "href":"https://api.spotify.com/v1/tracks/6NXW1J0rvUBX7JprJg31H3",
         "id":"6NXW1J0rvUBX7JprJg31H3",
         "is_local":False,
         "name":"Across the Sea",
         "popularity":43,
         "preview_url":"https://p.scdn.co/mp3-preview/1ef45aae01efa9f98df1efc14ebd367d9085ffe5?cid=26c35b7190da459584f5534423c51888",
         "track_number":1,
         "type":"track",
         "uri":"spotify:track:6NXW1J0rvUBX7JprJg31H3"
      },
      {
         "album":{
            "album_type":"SINGLE",
            "artists":[
               {
                  "external_urls":{
                     "spotify":"https://open.spotify.com/artist/7pXu47GoqSYRajmBCjxdD6"
                  },
                  "href":"https://api.spotify.com/v1/artists/7pXu47GoqSYRajmBCjxdD6",
                  "id":"7pXu47GoqSYRajmBCjxdD6",
                  "name":"Vulfpeck",
                  "type":"artist",
                  "uri":"spotify:artist:7pXu47GoqSYRajmBCjxdD6"
               }
            ],
            "external_urls":{
               "spotify":"https://open.spotify.com/album/3DiHrdZ5z0AqW6JTpLAKxG"
            },
            "href":"https://api.spotify.com/v1/albums/3DiHrdZ5z0AqW6JTpLAKxG",
            "id":"3DiHrdZ5z0AqW6JTpLAKxG",
            "images":[
               {
                  "height":640,
                  "url":"https://i.scdn.co/image/ab67616d0000b273ffce27a5dbb342d2c2d738c4",
                  "width":640
               },
               {
                  "height":300,
                  "url":"https://i.scdn.co/image/ab67616d00001e02ffce27a5dbb342d2c2d738c4",
                  "width":300
               },
               {
                  "height":64,
                  "url":"https://i.scdn.co/image/ab67616d00004851ffce27a5dbb342d2c2d738c4",
                  "width":64
               }
            ],
            "name":"Fugue State",
            "release_date":"2014-08-26",
            "release_date_precision":"day",
            "total_tracks":6,
            "type":"album",
            "uri":"spotify:album:3DiHrdZ5z0AqW6JTpLAKxG"
         },
         "artists":[
            {
               "external_urls":{
                  "spotify":"https://open.spotify.com/artist/7pXu47GoqSYRajmBCjxdD6"
               },
               "href":"https://api.spotify.com/v1/artists/7pXu47GoqSYRajmBCjxdD6",
               "id":"7pXu47GoqSYRajmBCjxdD6",
               "name":"Vulfpeck",
               "type":"artist",
               "uri":"spotify:artist:7pXu47GoqSYRajmBCjxdD6"
            }
         ],
         "disc_number":1,
         "duration_ms":155667,
         "explicit":False,
         "external_ids":{
            "isrc":"TCABZ1466844"
         },
         "external_urls":{
            "spotify":"https://open.spotify.com/track/0e3Ss9QHdiGCyOst88pilL"
         },
         "href":"https://api.spotify.com/v1/tracks/0e3Ss9QHdiGCyOst88pilL",
         "id":"0e3Ss9QHdiGCyOst88pilL",
         "is_local":False,
         "name":"Sky Mall",
         "popularity":46,
         "preview_url":"https://p.scdn.co/mp3-preview/c679e542b3b077035941dbe092e8ad973a384509?cid=26c35b7190da459584f5534423c51888",
         "track_number":4,
         "type":"track",
         "uri":"spotify:track:0e3Ss9QHdiGCyOst88pilL"
      },
   ],
   "total":50,
   "limit":20,
   "offset":0,
   "href":"https://api.spotify.com/v1/me/top/tracks",
   "previous":"None",
   "next":"https://api.spotify.com/v1/me/top/tracks?limit=20&offset=20"
}